### ISSUE TITLE
Add Nate to People section

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#107]
Can we get a picture of Nate (and a funny picture) to put on the `People` section of the `About` page?

**Comment by fernandogelin** [comment]
@paulstey Could you or someone with a good phone take a picture of him? Then just assign to @Rashi1997 or @TiffL and send the photos to them via slack.

**Comment by paulstey** [comment]
@alee35 : As our Senior Director of Photography Operations (SDPO), can I put you in charge of getting a picture of Nate?

**Comment by paulstey** [comment]
@n8wood-brown and @alee35, 

I just wanted to check in on this. Can we get a photo and a "hover" photo for the site?

-Paul

**Comment by ashleysyg** [comment]
@paulstey On it.

**Comment by ashleysyg** [comment]
@fernandogelin The images of Nate are in teh ccv-portraits folder. (https://drive.google.com/drive/u/0/folders/1z1witUrzW4sbbrYjj4VW3RlNtTq-6LA9)

**Comment by paulstey** [comment]
@ashleysyg : Thank you!!

**Comment by Rashi1997** [comment]
@fernandogelin @paulstey  I would need full name, team, subteam, title, GitHub username, bio(if possible) and weight (in which order to place) for Nate.

**Comment by fernandogelin** [comment]
@Rashi1997 

```
- name:  Nathan Wood
  weight:  (order of card, first order by team, then by first name)
  type: Full Time
  team: CCV Operations
  title: Senior Research Systems Administrator
  github_username: n8wood-brown 
  brown_directory_uuid: 857b928c-2ce1-fb2a-cde7-1a4ff21fa2d3
  bio: 
  image: <name>_main.jpg
```
