### ISSUE TITLE
[DATA] Add Kuba to intern section

### ISSUE THREAD

**Issue by fernandogelin** [brown-ccv/ccv-website-hugo#160]
**What would you like to update**
- [x] people
- [ ] opportunities

**If people, complete the object below. If adding new people, either add the images to this issue or send a slack message in `gh-ccv-website` after submitting this issue.**   

```
- name: Kuba Tarlowski
  weight:  (order of card, first order by team, then by first name)
  type: CCV Interns
  team: CCV Operations
  subteam: 
  title: Services Support Intern
  github_username: kubatarlowski 
  brown_directory_uuid: 154c611f-7b29-4209-9bf3-5e731cf360ea
  bio: 
  image: <name>_main.jpg
```

@ashleysyg can you work with @kubatarlowski to get his photo.

@kubatarlowski @mttunca Can you check the information above and edit the issue if necessary?
