### ISSUE TITLE
[DATA] Add Yang Liu to People

### ISSUE THREAD

**Issue by fernandogelin** [brown-ccv/ccv-website-hugo#168]
**What would you like to update**
- [x] people
- [ ] opportunities

**If people, complete the object below. If adding new people, either add the images to this issue or send a slack message in `gh-ccv-website` after submitting this issue. **   

```
- name: Yang Liu
  weight:  (order of card, first order by team, then by first name)
  type: Full Time
  team: CCV Operations
  title: Research Service Center Manager
  github_username: TBD
  brown_directory_uuid: e0e55df3-9f2c-4a12-a1de-742955164e1e
  bio: 
  image: <name>_main.jpg
```

Need photo, github username
