### ISSUE TITLE
[DATA] Add Bradford to People section

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#184]
**What would you like to update**
- [x] people
- [ ] opportunities

**If people, complete the object below. If adding new people, either add the images to this issue or send a slack message in `gh-ccv-website` after submitting this issue. **   

```
- name: Bradford Roarr
  weight:  (order of card, first order by team, then by first name)
  type: 
  team: Advanced Research Computing
  subteam: Data & Visualization
  title: Senior Research Software Engineer
  github_username: broarr
  brown_directory_uuid: 0adf6ab4-8d56-410a-8ac6-4b4ca136a534
  bio: 
  image: <name>_main.jpg
```

**If opportunities:**  
```
- title: 
  team: 
  subteam: 
  link:
```
*link from jobs@brown site*
