### ISSUE TITLE
[DATA] Add Kirk Brown to people section

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#197]
**What would you like to update**
- [x] people
- [ ] opportunities

**If people, complete the object below. If adding new people, either add the images to this issue or send a slack message in `gh-ccv-website` after submitting this issue. **   

```
- name: Kirk Brown
  weight:  (order of card, first order by team, then by first name)
  type: Full Time
  team: CCV Operations
  subteam: 
  title: Research Computing Analyst
  github_username:  NA
  brown_directory_uuid: 1c597441-90f8-4543-8627-d11dcd0dbdb0
  bio: 
  image: <name>_main.jpg
```
