### ISSUE TITLE
[DATA] Add Matt Slivinski to People section

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#274]
**What would you like to update**
- [x] people
- [ ] opportunities

**If people, complete the object below. If adding new people, either add the images to this issue or send a slack message in `gh-ccv-website` after submitting this issue. **   

```
- name: 
  weight:  (order of card, first order by team, then by first name)
  type: 
  team: 
  subteam: 
  title: 
  github_username: 
  brown_directory_uuid: 
  bio: 
  image: <name>_main.jpg
```

**If opportunities:**  
```
- title: 
  team: 
  subteam: 
  link:
```
*link from jobs@brown site*
