### ISSUE TITLE
[DATA] Add Fernando Cisneros to People

### ISSUE THREAD

**Issue by aguang** [brown-ccv/ccv-website-hugo#368]
**What would you like to update**
- [x] people
- [ ] opportunities

**If people, complete the object below. If adding new people, either add the images to this issue or send a slack message in `gh-ccv-website` after submitting this issue. **   

```
- name: Fernando Cisneros
  weight: CCV Interns, Fernando
  type: 
  team: Computational Biology Core 
  subteam: 
  title: Software Engineering Intern
  github_username: Nando1014
  brown_directory_uuid: 
  bio: 
  image: <name>_main.jpg
```

I don't really know the rest of the information but Slack me if you need it!

**If opportunities:**  
```
- title: 
  team: 
  subteam: 
  link:
```
*link from jobs@brown site*
