### ISSUE TITLE
[DATA] | Add Robert Gemma to people

### ISSUE THREAD

**Issue by RobertGemmaJr** [brown-ccv/ccv-website-hugo#407]
**What would you like to update**
- [ ] people

I would prefer to have the `Gemma_Funny` photo be my secondary photo but I totally understand if you don't want that many URI logos in my pictures. If so, the `Gemma_Funny_2` photo works great too! 😄 

```yml
- name: Robert Gemma, Jr.
  weight: "11"
  type: Full Time
  team: Advanced Research Computing
  subteam: Data & Visualization
  title: Research Software Engineer
  github_username: RobertGemmaJr
  brown_directory_uuid: e78668ed-0e7a-4e5f-a69e-ab4a5015961c
  bio: ""
  image: robert_main.jpg
```
![Gemma_Main](https://user-images.githubusercontent.com/38439940/135878174-4286ca09-9dbc-4b5b-99ed-89d48fe0f56c.jpg)
![Gemma_Funny](https://user-images.githubusercontent.com/38439940/135878175-b9a4c4bf-29d7-4b2e-85a6-9e06c2edbc49.jpg)
![Gemma_Funny_2](https://user-images.githubusercontent.com/38439940/135878178-8ec7f053-3f63-4054-a5d4-4b8af74d075c.jpg)
