### ISSUE TITLE
Create a page for interns

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/ccv-website-hugo#57]

**Comment by fernandogelin** [comment]
Format:
```
- name: 
  team: Advanced Research Computing or Operations
  subteam: Data & Visualization, Computational Biology Core, HPC, or Institutional Data
  title: 
  github_username: 
  brown_directory_uuid: 
  image: we need photos (main and hover)
```
